version: "3.9"
services:
  mongo:
    image: mongo:5.0.6-focal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS:-}
    ports:
      - 27017:27017/tcp
  mongo_express:
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8081:8081/tcp
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER:-}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS:-}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER:-}:${MONGO_PASS:-}@mongo/
    depends_on:
      - mongo
  redis:
    image: redis:6.2.6-bullseye
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS:-}
    ports:
      - 6379:6379/tcp
    volumes:
      - $PWD/redis-data:/var/lib/redis-data
      - $PWD/config/redis.conf:/usr/local/etc/redis/redis.conf
