version: '3.9'
services:
    postgres:
        image: postgres:14beta2-buster
        container_name: svc_postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=ea
            - POSTGRES_DB=ea
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432/tcp
    pgadmin:
        image: dpage/pgadmin4:5.6
        container_name: svc_pgadmin
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=postgres@localhost.dev
            - PGADMIN_DEFAULT_PASSWORD=postgres
            - PGADMIN_LISTEN_ADDRESS=0.0.0.0
            - PGADMIN_LISTEN_PORT=5480
        ports:
            - 5480:5480/tcp

volumes:
    db-data:

networks:
    default:
        external: true
        name: ea-intranet
