version: "3.9"
services:
  mongo:
    image: mongo:5.0.6-focal
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017/tcp
