version: '3.9'
services:
  hydra:
    image: oryd/hydra:v1.10.7
    restart: unless-stopped
    environment:
      - SECRETS_SYSTEM=$HYDRA_SECRET
      - DSN=$HYDRA_DSN
      - URLS_SELF_ISSUER=https://localhost:4444/
      - URLS_CONSENT=http://localhost:9020/consent
      - URLS_LOGIN=http://localhost:9020/login
    ports:
      - 4444:4444/tcp
      - 4445:4445/tcp
