version: "3.9"
services:
    mongo:
        image: mongo:5.0.6-focal
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
        ports:
            - 27017:27017/tcp
    redis:
        image: redis:6.2.6-bullseye
        command: redis-server /usr/local/etc/redis/redis.conf --requirepass pass
        ports:
            - 6379:6379/tcp
        volumes:
            - $PWD/redis-data:/var/lib/redis-data
            - $PWD/config/redis.conf:/usr/local/etc/redis/redis.conf
