[package]
name = "ea_core"
version = "0.1.0"
edition = "2018"

[dependencies]
deadpool-postgres = "0.7"
dotenv = "0.15"
tokio = { version = "1.4", features = ["rt-multi-thread", "macros", "time"] }
tokio-postgres = { version = "0.7", features = ["with-uuid-0_8", "with-serde_json-1", "with-chrono-0_4"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
prost-types = "0.8"
