[package]
name = "ea_proto_derive"
version = "0.1.1"
authors = ["ffimnsr <ffimnsr@gmail.com>"]
edition = "2021"
publish = false

[lib]
name = "ea_proto_derive"
proc-macro = true

[[test]]
name = "tests"
path = "tests/progress.rs"

[[test]]
name = "workshop"
path = "tests/workshop.rs"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["extra-traits"] }
inflector = { git = "https://github.com/fzrepo/inflector", branch = "master" }

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }
tokio = { version = "1.4", features = ["rt-multi-thread", "macros", "time"] }
tokio-postgres = { version = "0.7", features = ["with-uuid-0_8", "with-serde_json-1", "with-chrono-0_4"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
ea_core = { version = "0.1", path = "../ea_core" }
prost-types = "0.8"
tonic = "0.5"
log = "0.4"
prost = "0.8"

[build-dependencies]
tonic-build = "0.5"
