[package]
name = "ea_sql_derive"
version = "0.1.1"
authors = ["ffimnsr <ffimnsr@gmail.com>"]
edition = "2018"
publish = false

[lib]
name = "ea_sql_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
