[package]
name = "account_svc"
version = "0.1.0"
edition = "2018"
authors = ["ffimnsr <ffimnsr@gmail.com>"]
publish = false
description = "The account service"
homepage = "https://vastorigins.org"
readme = "README.md"

[dependencies]
deadpool-postgres = "0.7"
dotenv = "0.15"
log = "0.4"
env_logger = "0.8"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.4", features = ["rt-multi-thread", "macros", "time"] }
tokio-postgres = { version = "0.7", features = ["with-uuid-0_8", "with-serde_json-1", "with-chrono-0_4"] }
prost = "0.8"
prost-types = "0.8"
tonic = "0.5"
uuid = { version = "0.8", features = ["serde", "v4"] }
nanoid = "0.4"

inflector = { git = "https://github.com/fzrepo/inflector", branch = "master" }
ea_sql_derive = { version = "0.1", path = "../ea_sql_derive" }

[build-dependencies]
tonic-build = "0.5"
