[config]
skip_core_tasks = true
min_version = "0.35.8"

[env]
PROJECT_VERSION = "${CARGO_MAKE_PROJECT_VERSION}"

[tasks.build]
script = '''
docker build --force-rm \
    -f ./Dockerfile \
    --build-arg service_version=${PROJECT_VERSION} \
    --build-arg build-date=$(date --iso-8601=seconds -u) \
    --build-arg vcs_ref=$(git rev-parse --short HEAD) \
    -t ghcr.io/ffimnsr/ea-rs/ea_account:${PROJECT_VERSION}
    -t ghcr.io/ffimnsr/ea-rs/ea_account:latest ../..
'''

[tasks.push]
script = '''
docker image push -a ghcr.io/ffimnsr/ea-rs/ea_account
'''

[tasks.clean]
script = '''
docker system prune --volumes -f
docker image prune -a --filter="until=1h" --filter "label=org.label-schema.name=ea_account" -f
'''

[tasks.load]
script = '''
ssh -T sandbox << EOF
docker pull ghcr.io/ffimnsr/ea-rs/ea_account:${PROJECT_VERSION}
docker images
EOF
'''

[tasks.run]
script = '''
ssh -T sandbox << EOF
docker stop account-server && docker rm account-server
docker run -d --name account-server \
    -p 8010:8010/tcp \
    -e DSN=${DSN} \
    --restart always \
    ghcr.io/ffimnsr/ea-rs/ea_account:${PROJECT_VERSION}
EOF
'''

[tasks.push-manual]
script = '''
docker save ghcr.io/ffimnsr/ea-rs/ea_account:${PROJECT_VERSION} | pv | bzip2 > ./images/ea_account.tar.bz2
rsync -avzP ./images/ea_account.tar.bz2 sandbox:~/ea_account.tar.bz2
'''

[tasks.load-manual]
script = '''
ssh -T sandbox "pv ~/ea_account.tar.bz2 | bunzip2 | docker load"
'''

[tasks.deploy]
dependencies = [ "build", "push", "clean" ]
