[package]
name = "ea_trident"
version = "0.1.1"
edition = "2021"

[dependencies]
log = "0.4"
dotenv = "0.15"
base64 = "0.13"
tokio = { version = "1.4", features = ["rt-multi-thread", "macros", "time"] }
hyper = { version = "0.14", features = ["full"] }
routerify = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mongodb = "2.1"
uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
bson = { version = "2.1", features = ["uuid-0_8", "chrono-0_4"] }
